version: "3.9"  # optional since v1.27.0
services:
  node-red:
    image: nodered/node-red:3.0.1
    restart: always
    network_mode: "host"
    volumes:
      - "$HOME/node-red:/data"
    user: "0"
  dataloader:
    image: baozhu/node-red-dataloader:v1.2
    restart: always
    runtime: nvidia
    network_mode: "host"
    privileged: true
    devices:
    - "/dev:/dev"
    - "/var/run/udev:/var/run/udev"
  detection:
    image: baozhu/node-red-detection:v1.2
    restart: always
    runtime: nvidia
    network_mode: "host"
